//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcProViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcProViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://viewer.riverscapes.net/about/acknowledgements/.
        /// </summary>
        internal static string AcknowledgementsURL {
            get {
                return ResourceManager.GetString("AcknowledgementsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RiverscapesViewer.
        /// </summary>
        internal static string AppDataFolder {
            get {
                return ResourceManager.GetString("AppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbology\arcpro.
        /// </summary>
        internal static string AppDataSymbologyFolder {
            get {
                return ResourceManager.GetString("AppDataSymbologyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string AppDataSymbologySharedFolder {
            get {
                return ResourceManager.GetString("AppDataSymbologySharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riverscapes Viewer for ArcGIS Pro.
        /// </summary>
        internal static string ApplicationNameLong {
            get {
                return ResourceManager.GetString("ApplicationNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riverscapes Viewer.
        /// </summary>
        internal static string ApplicationNameShort {
            get {
                return ResourceManager.GetString("ApplicationNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basemaps.
        /// </summary>
        internal static string BasemapsLabel {
            get {
                return ResourceManager.GetString("BasemapsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaveBusinessLogic.
        /// </summary>
        internal static string BusinessLogicXMLFolder {
            get {
                return ResourceManager.GetString("BusinessLogicXMLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://viewer.riverscapes.net/.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://data.riverscapes.net.
        /// </summary>
        internal static string DataWarehouseURL {
            get {
                return ResourceManager.GetString("DataWarehouseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://viewer.riverscapes.net.
        /// </summary>
        internal static string HelpBaseURL {
            get {
                return ResourceManager.GetString("HelpBaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://viewer.riverscapes.net/.
        /// </summary>
        internal static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Riverscapes/RaveAddIn/issues.
        /// </summary>
        internal static string NewIssueURL {
            get {
                return ResourceManager.GetString("NewIssueURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xml.riverscapes.net/.
        /// </summary>
        internal static string ResourcesURL {
            get {
                return ResourceManager.GetString("ResourcesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] viewer16 {
            get {
                object obj = ResourceManager.GetObject("viewer16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://viewer.riverscapes.net.
        /// </summary>
        internal static string WebSiteURL {
            get {
                return ResourceManager.GetString("WebSiteURL", resourceCulture);
            }
        }
    }
}
